name: maquinaJAVA
on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Comprobar codigo repositorio
        run: myci-actions/checkout@8

      - name: Crear carpeta en el servidor AWS
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_KEY }}
          port: ${{ secrets.AWS_PORT }}
          script: |
                    mkdir -p /home/ubuntu/maquinaJAVA

      - name: Sincronizar archivos al servidor AWS
        uses: burnett01/rsync-deployments@7.0.2
        with:
          switches: "-avz --delete -e 'ssh -i ${{ secrets.AWS_KEY }} -p ${{ secrets.AWS_PORT }} -o StrictHostKeyChecking=no -o LogLevel=ERROR'"
          path: "./"
          remote_host: ${{ secrets.AWS_HOST }}
          remote_user: ${{ secrets.AWS_USER }}
          remote_path: "/home/ubuntu/maquinaJAVA/"
          remote_key: ${{ secrets.AWS_KEY }}
          remote_port: ${{ secrets.AWS_PORT }}

      - name: Levantar docker-compose
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_KEY }}
          port: ${{ secrets.AWS_PORT }}
          script: |
                    cd /home/ubuntu/maquinaJAVA/
                    sudo docker compose down
                    sudo docker compose up -d --build