name: maquinaJAVA
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Crear archivo de clave privada
        run: |
          echo "${{ secrets.AWS_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Crear carpeta en el servidor AWS
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_KEY }}
          port: ${{ secrets.AWS_PORT }}
          script: |
            mkdir -p /home/ubuntu/maquinaJAVA

      - name: Sincronizar archivos al servidor AWS
        run: |
          rsync -avz --delete -e "ssh -i private_key.pem -p ${{ secrets.AWS_PORT }} -o StrictHostKeyChecking=no -o LogLevel=ERROR" ./ ${{ secrets.AWS_USER }}@${{ secrets.AWS_HOST }}:/home/ubuntu/maquinaJAVA/

      - name: Levantar docker-compose
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_KEY }}
          port: ${{ secrets.AWS_PORT }}
          script: |
            cd /home/ubuntu/maquinaJAVA/microServicioFactura/microServicioFactura/
            sudo docker compose down || true
            sudo docker compose up -d --build